Feat/werzeug sebastian
VanDulti/PixelLuxe pull request #12
Opened 2024-05-04 15:13 UTC by Biter01

Added:
new package tools
 -Brush.java 
 -WorkingTool.java

 new package dialog
    -DrawDialog.java

You can now select a color and a brush size and paint with the brush. 
Working Area has now the possibiltiy to execute every new Tool which has implemented the new WorkingTool interface

2024-05-04 15:39 UTC, Biter01 commented
Added the new Files

2024-05-04 17:29 UTC, VanDulti commented
Strg + Alt + L in allen Files

2024-05-04 17:46 UTC, VanDulti requested changes

2024-05-04 17:46 UTC, VanDulti commented on pixelluxe-gui/src/main/java/at/jku/pixelluxe/ui/WorkingArea.java
> +		private static WorkingTool tool = null;
static 🥶

2024-05-04 17:46 UTC, VanDulti commented on pixelluxe-gui/src/main/java/at/jku/pixelluxe/ui/WorkingArea.java
> +			tool= toolee;
😳

2024-05-04 17:46 UTC, VanDulti commented on pixelluxe-gui/src/main/java/at/jku/pixelluxe/ui/WorkingArea.java
> +			new Rectangle();
...

2024-05-08 17:31 UTC, VanDulti approved these changes

2024-05-10 18:47 UTC, merged